### ISSUE TITLE
Covers and Wind Alarm

### ISSUE THREAD

**Issue by Karssi** [XKNX/xknx#72]
Hi Julius,

I just stumbled on a minor cosmetic issue with Covers during a Wind Alarm/Block.
If I issue a down command during a Wind Alarm block HAss will show, both by slider movement and after runtime (calculated reaching of 100% closed) the greying out of the down arrow, that the cover is moving when actually it is locked in the up position.
Would it be possible for the xknx component to look at the "Status of Movement" address (1bit DPT 1.010 start/stop) to determine if the cover is actually moving?

**Comment by Julius2342** [comment]
is this status of movement actively pushed?

(to be honest, i actually do not really know how to actively handle this ..)

My covers actively send out the position address when the cover is stopped. This status is used to stop the travel-calculator and move the slider to the current position. Do your covers do the same)

**Comment by TinusK** [comment]
The problem here is that hass does not know that the cover is blocked. If you press the down arrow, the knx down command is send to the bus but the cover stays in its current position (movement is blocked) and therefor a position is not returned to the bus (while the cover is blocked, the actor simply ignores the move command).

To solve this, a block address needs to be given to the xknx (e.g. block_address=3/4/5) and if this address equals '1' then all cover buttons needs to be greyed out until the address becomes '0'.

Or maybe an other, more simpler solution is possible but I cant think of it at the moment :)

**Comment by Julius2342** [comment]
ah! got it. So the alarm is not issued during movement, it happens some time before and should disable the whole component.

**Comment by Karssi** [comment]
Yes, Tinusk is correct. An additional address for Block would be great.
As soon as a cover is blocked (by high wind or low temperature) this will turn to '1'.

**Comment by marvin-w** [comment]
@farmio was so kind and opened the necessary architecture issue in home assistant. Right now it's not possible for us to block covers in the frontend. 

We could implement the block address but it wouldn't have any visual impact on HA unless the architecture change gets approved in which case we could proceed here.

Issue: https://github.com/home-assistant/architecture/issues/429

**Comment by da-anda** [comment]
would it be possible to already add support for alarm/lock state GAs in XKNX and at least show them as attributes?
