### ISSUE TITLE
warnings in log "Error: KNX bus did not respond in time (2.0 secs) to GroupValueRead"

### ISSUE THREAD

**Issue by pswid** [XKNX/xknx#871]
I'm using the HA for few months already and I see such warning/s in log after each restart in every HA version, including the latest 2022.2.7. The problems seems to be related to slow processing data by HomeAssistant not by KNX devices. My PC should be fast enough (Generic x86-64 HA OS running on celeron N2808 NUC). Connection to the KNX bus is via KNX/IP router (routing mode).

One example from my debug (I've removed irrelevant log entries):

```
12:32:59 [xknx.state_updater] StateUpdater reading 5/3/177 for RTC room 2 temp. - Value
12:33:02 [xknx.telegram] <Telegram direction="Outgoing" source_address="0.0.0" destination_address="5/3/177" payload="<GroupValueRead />" />
12:33:02 [xknx.log] Error: KNX bus did not respond in time (2.0 secs) to GroupValueRead request for: 5/3/177
12:33:02 [xknx.log] Could not sync group address '5/3/177' (RTC room 2 temp. - Value)
12:33:05 [xknx.telegram] <Telegram direction="Incoming" source_address="1.2.115" destination_address="5/3/177" payload="<GroupValueResponse value="<DPTArray value="[0xc,0x8d]" />" />" />
```

as you can see, telegram GroupValueRead was sent to KNX bus only 3s after StateUpdater and **exactly at the same time** the error is reported! Log also shows that response from KNX was received 3s after GroupValeRead (so 2.0s timeout is definitely too small), but, as I see in ETS bus monitor, GroupValeuResponse has been sent to KNX almost immediatelly after GroupValueRead (only ~200ms delay). Why HA shows that it took 3s?

In my opinion three things should help with solving "KNX bus did not respond in time (2.0 secs)" warnings:
- timeouts should start at the moment of sending GroupRead telegram to the KNX bus and not immediatelly after "stateupdater reading"
- increasing timoeuts (to 5s?)
- increasing speed of KNX processing by HomeAssistant itself

**Comment by farmio** [comment]
Hi 👋!

Generally speaking there is nothing in between the StateUpdater requesting a read and the socket sending out the read request. But if there is a lot going on - like at the start of HA - or if there is  some code blocking the event loop, the execution of these parts can be stalled for some time.
If these warnings only occur on HA startup I'd suggest to just ignore them.

> timeouts should start at the moment of sending GroupRead telegram to the KNX bus and not immediatelly after "stateupdater reading"

Valid point, unfortunately not that stratight-forward to implement. In case of a blocked event loop it would also just solve half of the problem since we would also get delayed callbacks from the sockets.

> increasing timoeuts (to 5s?)

We use timeouts specified in the KNX specifications. Unfortunately I don't recall where this is defined exactly. We already increased it from 1 second to 2 seconds in 0.15.4

> increasing speed of KNX processing by HomeAssistant itself

Great idea. We are open for suggestions and PRs 🤷
